# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_pb2 as grpc__pb2


class imageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.image = channel.unary_unary(
                '/imageService/image',
                request_serializer=grpc__pb2.imageMessage.SerializeToString,
                response_deserializer=grpc__pb2.addMessage.FromString,
                )


class imageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_imageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'image': grpc.unary_unary_rpc_method_handler(
                    servicer.image,
                    request_deserializer=grpc__pb2.imageMessage.FromString,
                    response_serializer=grpc__pb2.addMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class imageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageService/image',
            grpc__pb2.imageMessage.SerializeToString,
            grpc__pb2.addMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class addServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addService = channel.unary_unary(
                '/addService/addService',
                request_serializer=grpc__pb2.addMessage.SerializeToString,
                response_deserializer=grpc__pb2.addMessage.FromString,
                )


class addServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_addServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addService': grpc.unary_unary_rpc_method_handler(
                    servicer.addService,
                    request_deserializer=grpc__pb2.addMessage.FromString,
                    response_serializer=grpc__pb2.addMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'addService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class addService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/addService/addService',
            grpc__pb2.addMessage.SerializeToString,
            grpc__pb2.addMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
