# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngrpc.proto\"\"\n\naddMessage\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1b\n\x0cimageMessage\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x32\x35\n\x0cimageService\x12%\n\x05image\x12\r.imageMessage\x1a\x0b.addMessage\"\x00\x32\x36\n\naddService\x12(\n\naddService\x12\x0b.addMessage\x1a\x0b.addMessage\"\x00\x62\x06proto3'
)




_ADDMESSAGE = _descriptor.Descriptor(
  name='addMessage',
  full_name='addMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='addMessage.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='addMessage.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=48,
)


_IMAGEMESSAGE = _descriptor.Descriptor(
  name='imageMessage',
  full_name='imageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='imageMessage.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['addMessage'] = _ADDMESSAGE
DESCRIPTOR.message_types_by_name['imageMessage'] = _IMAGEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addMessage = _reflection.GeneratedProtocolMessageType('addMessage', (_message.Message,), {
  'DESCRIPTOR' : _ADDMESSAGE,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:addMessage)
  })
_sym_db.RegisterMessage(addMessage)

imageMessage = _reflection.GeneratedProtocolMessageType('imageMessage', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMESSAGE,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:imageMessage)
  })
_sym_db.RegisterMessage(imageMessage)



_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='imageService',
  full_name='imageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=132,
  methods=[
  _descriptor.MethodDescriptor(
    name='image',
    full_name='imageService.image',
    index=0,
    containing_service=None,
    input_type=_IMAGEMESSAGE,
    output_type=_ADDMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['imageService'] = _IMAGESERVICE


_ADDSERVICE = _descriptor.ServiceDescriptor(
  name='addService',
  full_name='addService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=134,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='addService',
    full_name='addService.addService',
    index=0,
    containing_service=None,
    input_type=_ADDMESSAGE,
    output_type=_ADDMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDSERVICE)

DESCRIPTOR.services_by_name['addService'] = _ADDSERVICE

# @@protoc_insertion_point(module_scope)
